### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by jdmitrovic** [MATF-RG17/RG082-pipeline#1]

**Comment by ivan-cukic-matf** [comment]
Da li bi igra trebalo da radi, pošto kod mene ne rotira cevi?

**Comment by jdmitrovic** [comment]
Trebalo bi, ali igra počinje pauzirana, tako da tek kada se klikne "S" onda igra startuje. No cheating allowed.

**Comment by ivan-cukic-matf** [comment]
Kod mene zbog necega ne radi. Ako možete, napravite snimak pa okačite - uvek je bolje da 'odbrana' bude na studentskom računaru, a ne na mom.

**Comment by jdmitrovic** [comment]
Evo GIF-a. Još jedan kolega je proveravao na Ubuntu-u, i njemu funkcioniše, tako da stvarno ne znam gde bi mogao biti problem.

![output](https://user-images.githubusercontent.com/23086591/41432749-2becf6ca-7017-11e8-9d22-df8be727eb46.gif)

**Comment by ivan-cukic-matf** [comment]
U redu. Izgleda fino.
